version: '3'

services:
  fcm_api:
    build: ./api
    environment:
      - APP_NAME=fcm_api
    container_name: fcm_api
    ports:
      - "5000:5000"
  fcm_webserver:
    build: ./frontend
    container_name: fcm_webserver
    ports:
      - "80:80"
    depends_on:
      - fcm_api